### ISSUE TITLE
unicode handling error in item.py

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#106]
Feb 13 16:17:37 ti-core app/web.1:  ERROR                     MainThread totalimpact - Exception on /v1/item/doi/10.​1152/​ajpendo.​00395.​2006 [GET]
Feb 13 16:17:37 ti-core app/web.1:  Traceback (most recent call last):
..
Feb 13 16:17:38 ti-core app/web.1:  File "/app/totalimpact/views.py", line 159, in get_item_from_namespace_nid
Feb 13 16:17:38 ti-core app/web.1:  tiid = item_module.get_tiid_by_alias(namespace, nid, mydao)
Feb 13 16:17:38 ti-core app/web.1:  File "/app/totalimpact/item.py", line 437, in get_tiid_by_alias
Feb 13 16:17:38 ti-core app/web.1:  ns=ns, nid=nid))
Feb 13 16:17:38 ti-core app/web.1:  UnicodeEncodeError: 'ascii' codec can't encode character u'\u200b' in position 3: ordinal not in range(128)

**Comment by hpiwowar** [comment]
duplicate of #122
