### ISSUE TITLE
unicode problem in get_tiid_by_alias

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#122]
``````
Jun 17 10:48:25 ti-core app/web.2:  [6]    ERROR                     MainThread totalimpact - Exception on /v1/item/doi/10.1111/j.1439-0418.2005.00948.173–175 [GET] 
Jun 17 10:48:25 ti-core app/web.2:  Traceback (most recent call last): 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1292, in wsgi_app 
Jun 17 10:48:25 ti-core app/web.2:      response = self.full_dispatch_request() 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1062, in full_dispatch_request 
Jun 17 10:48:25 ti-core app/web.2:      rv = self.handle_user_exception(e) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1060, in full_dispatch_request 
Jun 17 10:48:25 ti-core app/web.2:      rv = self.dispatch_request() 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1047, in dispatch_request 
Jun 17 10:48:25 ti-core app/web.2:      return self.view_functions[rule.endpoint](**req.view_args) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.9.0.21/newrelic/api/object_wrapper.py", line 220, in __call__ 
Jun 17 10:48:25 ti-core app/web.2:      self._nr_instance, args, kwargs) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.9.0.21/newrelic/api/function_trace.py", line 81, in literal_wrapper 
Jun 17 10:48:25 ti-core app/web.2:      return wrapped(*args, **kwargs) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.9.0.21/newrelic/api/object_wrapper.py", line 220, in __call__ 
Jun 17 10:48:25 ti-core app/web.2:      self._nr_instance, args, kwargs) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.9.0.21/newrelic/api/transaction_name.py", line 51, in literal_wrapper 
Jun 17 10:48:25 ti-core app/web.2:      return wrapped(*args, **kwargs) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/totalimpact/views.py", line 176, in get_item_from_namespace_nid 
Jun 17 10:48:25 ti-core app/web.2:      api_user.register_item((namespace, nid), api_key, myredis, mydao, mypostgresdao) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/totalimpact/api_user.py", line 154, in register_item 
Jun 17 10:48:25 ti-core app/web.2:      tiid = item.get_tiid_by_alias(namespace, nid, mydao) 
Jun 17 10:48:25 ti-core app/web.2:    File "/app/totalimpact/item.py", line 459, in get_tiid_by_alias 
Jun 17 10:48:25 ti-core app/web.2:      ns=ns, nid=nid)) 
Jun 17 10:48:25 ti-core app/web.2:  UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 34: ordinal not in range(128) ```
``````

**Comment by hpiwowar** [comment]
fixed
