### ISSUE TITLE
need connection instructions

### ISSUE THREAD

**Issue by hpiwowar** [ourresearch/total-impact-core#2]
Tests in test_watchers.py are broken in a fresh pull.

It looks like this might be because the dao is expecting a database?  

from totalimpact.conf.json:    

```
# Database information
    "db_url" : "http://localhost:5984/",
    "db_name" : "ti",
```

If so, let's include installation instructions for the local database in the README or connect details to the remote database.

```
test_01_init_watcher (test.totalimpact.test_watchers.Test_Watchers) ... ok
test_02_init_metrics (test.totalimpact.test_watchers.Test_Watchers) ... ERROR
test_03_init_aliases (test.totalimpact.test_watchers.Test_Watchers) ... ERROR
test_04_alias_sleep (test.totalimpact.test_watchers.Test_Watchers) ... ERROR
test_05_metrics_sleep (test.totalimpact.test_watchers.Test_Watchers) ... ERROR

======================================================================
ERROR: test_02_init_metrics (test.totalimpact.test_watchers.Test_Watchers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hpiwowar/Documents/Projects/tiv2/total-impact/test/totalimpact/test_watchers.py", line 29, in test_02_init_metrics
    pmt = ProviderMetricsThread(provider, self.config)
  File "/Users/hpiwowar/Documents/Projects/tiv2/total-impact/totalimpact/watchers.py", line 117, in __init__
    QueueConsumer.__init__(self, MetricsQueue())
  File "/Users/hpiwowar/Documents/Projects/tiv2/total-impact/totalimpact/dao.py", line 13, in __init__
    self.couch, self.db = self.connection()
  File "/Users/hpiwowar/Documents/Projects/tiv2/total-impact/totalimpact/dao.py", line 26, in connection
    db = couch[couch_db]
  File "/Library/Python/2.6/site-packages/CouchDB-0.8-py2.6.egg/couchdb/client.py", line 137, in __getitem__
    db.resource.head() # actually make a request to the database
  File "/Library/Python/2.6/site-packages/CouchDB-0.8-py2.6.egg/couchdb/http.py", line 377, in head
    return self._request('HEAD', path, headers=headers, **params)
  File "/Library/Python/2.6/site-packages/CouchDB-0.8-py2.6.egg/couchdb/http.py", line 419, in _request
    credentials=self.credentials)
  File "/Library/Python/2.6/site-packages/CouchDB-0.8-py2.6.egg/couchdb/http.py", line 239, in request
    resp = _try_request_with_retries(iter(self.retry_delays))
  File "/Library/Python/2.6/site-packages/CouchDB-0.8-py2.6.egg/couchdb/http.py", line 205, in _try_request_with_retries
    raise e
error: [Errno 61] Connection refused
...

```

**Comment by richard-jones** [comment]
Good to include readme information for the database.

With regard to the unit tests, we will need to isolate the watchers from the DAO, so that the unit can be tested.  I am working on that today.

**Comment by hpiwowar** [comment]
Richard, unit testing the watcher and isolating it watchers from the DAO sounds very helpful indeed!  Could you let me know when you've done this bit, because it will definitely help me understand how the watcher works (and I'm guessing get us closer to and end-to-end working system).  

Actually, I'll make an extra ticket for this bit so I can easily follow it.

Thanks!

**Comment by hpiwowar** [comment]
Installation instructions for a local database are now in the README, and a separate ticket has been opened for isolating watchers from the DAO.
